### PR TITLE
Using ghcr registry for pulling `dependabot/dependabot-core` image

### LINKED ISSUE #20: `dependabot/dependabot-core` image cannot be found
Lastly I am getting the error detailed at the end of this issue.

[I have checked docker registry](https://hub.docker.com/search?q=dependabot) and ``dependabot/dependabot-core`` image does not exist. I guess something changed (dependabot developers pull out the image from docker registry?)

```text

##[debug]Starting: Build marcoroth/dependabot-bump-together-action@v0.3.1
Build container for action use: '/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1/Dockerfile'.
  /usr/bin/docker build -t ed866e:a421fe560fac47978d915f5d23c2d464 -f "/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1/Dockerfile" "/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1"
  Sending build context to Docker daemon  17.41kB
  
  Step 1/10 : FROM dependabot/dependabot-core
  pull access denied for dependabot/dependabot-core, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker build failed with exit code 1, back off 3.562 seconds before retry.
  /usr/bin/docker build -t ed866e:a421fe560fac47978d915f5d23c2d464 -f "/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1/Dockerfile" "/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1"
  Sending build context to Docker daemon  17.41kB
  
  Step 1/10 : FROM dependabot/dependabot-core
  pull access denied for dependabot/dependabot-core, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker build failed with exit code 1, back off 8.411 seconds before retry.
  /usr/bin/docker build -t ed866e:a421fe560fac47978d915f5d23c2d464 -f "/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1/Dockerfile" "/home/runner/work/_actions/marcoroth/dependabot-bump-together-action/v0.3.1"
  Sending build context to Docker daemon  17.41kB
  
  Step 1/10 : FROM dependabot/dependabot-core
  pull access denied for dependabot/dependabot-core, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Docker build failed with exit code 1
```

### PR DESCRIPTION
**Pull request by germa89**
Use the ghcr to pull ``dependabot/dependabot-core`` image. 

See: https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-core

close #20

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]

**Review by marcoroth — APPROVED** [review]
Thank you @germa89 for the pull request and for fixing this!

**Comment by germa89** [comment]
> Thank you @germa89 for the pull request and for fixing this!

Glad to help! :)

Let me know if I can help something else!

**Comment by domoritz** [comment]
@marcoroth could you make a release with this fix?

**Comment by marcoroth** [comment]
@domoritz just released [`0.3.2`](https://github.com/marcoroth/dependabot-bump-together-action/releases/tag/v0.3.2)

**Pull request merged**
